const Bankier = require('./bankier')

bankierA = new Bankier(3, 11, [3, 4, 3], [6, 6, 6])
bankierA.showAllData()
const isSafeA = bankierA.safetyAlgorithm()
console.log('----------------------------------')
console.log(`System 'A' is ${(isSafeA.isSafe)?'SAFE':'NOT SAFE'}`)
if (isSafeA.isSafe) console.log('Safe process sequence is', isSafeA.safeSequence)
console.log('----------------------------------')

bankierB = new Bankier(3, 11, [2, 5, 3], [6, 6, 6])
bankierB.showAllData()
const isSafeB = bankierB.safetyAlgorithm()
console.log('----------------------------------')
console.log(`System 'B' is ${(isSafeB.isSafe)?'SAFE':'NOT SAFE'}`)
if (isSafeB.isSafe) console.log('Safe process sequence is', isSafeB.safeSequence)
console.log('----------------------------------')